driver:
  name: vagrant
  customize:
    memory: 1024

provisioner:
  name: chef_zero
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
  - name: centos-6.8
    run_list:
      - recipe[selinux::disabled]
      - recipe[mysql_test::yum_repo]
  - name: centos-7.3
    run_list:
      - recipe[selinux::disabled]
      - recipe[mysql_test::yum_repo]
  - name: debian-7.11
  - name: debian-8.6
  - name: opensuse-13.2
  - name: opensuse-leap-42.2
  - name: fedora-24 # there is not a 25 repo yet
    run_list:
      - recipe[yum::dnf_yum_compat]
      - recipe[selinux::disabled]
      - recipe[mysql_test::yum_repo]
  - name: ubuntu-14.04
  - name: ubuntu-16.04

suites:
  #
  # client
  #
  - name: installation_client_package-51
    run_list:
    - recipe[mysql_test::installation_client]
    attributes:
      mysql:
       version: '5.1'
    includes: [
      'centos-6.8'
    ]

  - name: installation_client_package-55
    run_list:
    - recipe[mysql_test::installation_client]
    attributes:
      mysql:
       version: '5.5'
    includes: [
      'centos-6.8',
      'centos-7.3',
      'debian-7.11',
      'debian-8.6',
      'ubuntu-14.04'
    ]

  - name: installation_client_package-56
    run_list:
    - recipe[mysql_test::installation_client]
    attributes:
      mysql:
       version: '5.6'
    includes: [
      'centos-6.8',
      'centos-7.3',
      'fedora-24',
      'ubuntu-14.04',
      'opensuse-13.2',
      'opensuse-leap-42.2'
    ]

  - name: installation_client_package-57
    run_list:
    - recipe[mysql_test::installation_client]
    attributes:
      mysql:
       version: '5.7'
    includes: [
      'centos-6.8',
      'centos-7.3',
      'fedora-24',
      'ubuntu-16.04'
    ]


  #
  # smoke
  #
  - name: smoke51
    run_list:
    - recipe[mysql_test::smoke]
    attributes:
      mysql:
       version: '5.1'
    includes: [
      'centos-6.8'
     ]

  - name: smoke55
    run_list:
    - recipe[mysql_test::smoke]
    attributes:
      mysql:
       version: '5.5'
    includes: [
      'centos-6.8',
      'centos-7.3',
      'debian-7.11',
      'debian-8.6',
      'ubuntu-14.04'
     ]

  - name: smoke56
    run_list:
    - recipe[mysql_test::smoke]
    attributes:
      mysql:
       version: '5.6'
    includes: [
      'centos-6.8',
      'centos-7.3',
      'fedora-24',
      'ubuntu-14.04',
      'opensuse-13.2',
      'opensuse-leap-42.2'
     ]

  - name: smoke57
    run_list:
    - recipe[mysql_test::smoke]
    attributes:
      mysql:
       version: '5.7'
    includes: [
      'centos-6.8',
      'centos-7.3',
      'fedora-24',
      'ubuntu-16.04'
     ]
